<?php
namespace backend\module\question\controllers;

use yii\db\Exception;
use yii\web\Controller;
use yii\common\models\Question;
use yii\common\models\Type;
use yii\db\Query;
use yii\web\Response;
use yii\web\Request;

class IndexController extends Controller
{
    public function actionIndex()
    {
        return "question"; // TODO: Change the autogenerated stub
    }
    /*
     * 查找
     * 1:查找问题
     * 2：查找类型名
     * 3：模糊查找问题
     * 4；按照问题类型查找对应 问题
     */
    public function actionQuery()
    {
        $request = \Yii::$app->request;
        $flag = $request->post('flag');
        if($flag==1)
        {
            $query = (new Query())
                ->select('*')
                ->from('question')
                ->all();
            return array("data"=>$query,"msg"=>"全部问题");
        }
        else if($flag==2)
        {
            $query = (new Query())
                ->select('*')
                ->from('type')
                ->all();
            return array("data"=>$query,"msg"=>"全部类型");
        }
        else if($flag==3)
        {
            $search = $request->post('name');
            $query = (new Query())
                ->select('*')
                ->from('question')
                ->Where(['or',
                    ['like', 'title', $search],
                    ['like', 'content', $search],
                ])
                ->all();
            return array("data"=>$query,"msg"=>"查询".$search."问题");
        }
        else if($flag==4)
        {
            $id = $request->post('id');
            $query =(new Query())
                ->select('*')
                ->from('question')
                ->Where(['type'=>$id])
                ->all();
            return array("data"=>$query,"msg"=>$id."问题查找");
        }

    }

    public function actionAddquestion()
    {
        $request = \Yii::$app->request;
        $title = $request->post('title');
        $content = $request->post('content');
        $type = $request->post('type');
        $query = (new Query())
            ->select('*')
            ->from('question')
            ->Where(['title'=>$title])
            ->orWhere(['content'=>$content])
            ->all();
        if($query)
        {
            return array("data"=>$query,"msg"=>"该问题已存在");
        }
        $typeid = (new Query())
            ->select('*')
            ->from('type')
            ->Where(['typename'=>$type])
            ->one();
        $id = (new Query())
            ->select('*')
            ->from('question')
            ->max('id');
        $id = $id+1;
        $insertU = \Yii::$app->db->createCommand()->insert('question',array('id'=>$id,'title'=>$title,'content'=>$content,'type'=>$typeid['id']))->execute();
    }

}

